name: Deploy Coblux

on:
  push:
    branches:
      - main  # ou a branch que você estiver usando

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v2

      - name: Instalar dependências
        run: npm install

      - name: Rodar build
        run: npm run build

      - name: Deploy para Netlify
        uses: nwtgck/actions-netlify@v1.2.3
        with:
          publish-dir: './dist'  # ou build, dependendo do seu framework
          production-branch: main
          deploy-message: 'Deploy automático pelo Coblux'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
